### ISSUE TITLE
The second voice is always delayed in the midi playback.

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#422] opened 2022-12-30 15:58 UTC
**Description**
A description of what the bug is.

**To Reproduce**
Steps to reproduce the issue.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
If applicable, include your operating system (e.g. Windows 10) and which version of Power Tab Editor (e.g. Alpha 12) you are using

**Comment by cameronwhite** [comment] 2022-12-30 17:29
Possibly a duplicate of #423, but I really need example files and steps to reproduce in order to do anything with this.
Please also ensure that you're using the latest release

**Comment by cameronwhite** [comment] 2023-07-16 02:33
Closing as this could not be reproduced

**Closed by cameronwhite** 2023-07-16 02:33 UTC
Labels: bug, info needed
