### ISSUE TITLE
Show only tabs of one instrument

### ISSUE THREAD

**Issue by guitarslayer97** [powertab/powertabeditor#302] opened 2020-07-01 20:27 UTC
Hi, I just downloaded your code to view .gp files (Guitar Pro 7) and I am very happy that it works. Thank you for your great work!
I couldn't find out if there is any possibility to just show the tabs of one instrument? Right now, all of the contributing instruments are on the pages, which makes it impossible for me to see the next line of my guitar tabs (because I can only see the current line of the guitar tab which I want to read). 
Thank you in advance for your answer!

**Comment by guitarslayer97** [comment] 2020-07-01 20:33
Edit: I've just recognized that this was issued in the post below this one. Can maybe anyone describe how to add a filter to see just one instrument at a time, e.g. the lead guitar? Cheers!

**Comment by cameronwhite** [comment] 2020-07-01 23:08
Thanks for submitting this and doing some testing! I've left some notes in https://github.com/powertab/powertabeditor/issues/301#issuecomment-652688132 on how to set it up, so I'll close this issue as a duplicate of the other feature request

**Closed by cameronwhite** 2020-07-01 23:08 UTC
Labels: enhancement
