### ISSUE TITLE
Cannot Tie Notes Between Systems

### ISSUE THREAD

**Issue by Secondary-Type** [powertab/powertabeditor#283] opened 2020-05-07 18:56 UTC
![BugPT2](https://user-images.githubusercontent.com/64983907/81333514-59751580-906a-11ea-9c15-4a95a0acd588.png)
The tied note function isn't working between systems. Is this a program limitation or is there a workaround I don't know about? I cannot tie the final note of measure 84 with the first note of measure 85.

**Comment by cameronwhite** [comment] 2020-05-07 23:52
Yeah, this is a limitation - I think this is a duplicate of #27

**Closed by cameronwhite** 2020-05-07 23:52 UTC

**Comment by cameronwhite** [comment] 2020-07-07 00:08
This issue is fixed for the next release (see #27)
