### ISSUE TITLE
Hammer/Pull-off key command on Mac

### ISSUE THREAD

**Issue by theczar** [powertab/powertabeditor#162] opened 2015-01-30 12:19 UTC
Hey, I'm using Macbook Pro and was wondering why I have to press fn+H to get hammer/pull-off? Why H alone won't work? Some other commands like P, Y, S work like they should, without the fn-key.

**Comment by cameronwhite** [comment] 2015-01-31 04:15
No idea why that would be happening - I haven't heard of anyone else hitting this issue. Can you open the   Customize Shortcuts dialog and try out some different shortcuts for that command?

**Comment by theczar** [comment] 2015-01-31 08:50
Yes, I tried different key commands and they all require me to press fn+letter. But this only happens with hammer/pull-off, the rest seem to be ok. So weird.

**Comment by theczar** [comment] 2015-02-12 21:20
Kind of related to this issue: the score polisher key command Shift + J won't work, but Shift + fn + J works. Tried with other letters too, but plain Shift + key just doesn't work, always requires the fn there too.

**Comment by cameronwhite** [comment] 2020-05-28 00:48
I can't reproduce this on my OSX machine with the latest release, so I think I'll close it. It may have been due to an old Qt version or something like that.

**Closed by cameronwhite** 2020-05-28 00:48 UTC
Labels: C-osx, T-bug
