### ISSUE TITLE
Playback is too slow

### ISSUE THREAD

**Issue by Malethar** [powertab/powertabeditor#214] opened 2016-03-03 22:21 UTC
The playback of tabs way too slow. If you export the midi or use any other tab playback software, you'll notice that it's played way faster than in PTE.

**Comment by cameronwhite** [comment] 2016-03-05 21:23
Do you have a specific tab that has this problem? It seems okay for me (on OSX) - I timed using a stopwatch how long it took to play a few bars in PTE vs Guitar Pro, and the difference was negligible.

**Comment by Malethar** [comment] 2016-03-05 22:37
on Windows 10, it's 20 bpm slower

**Comment by cameronwhite** [comment] 2016-03-05 23:36
OK, I'll give it a try on my Windows machine later

**Comment by Canaanabolaanan** [comment] 2016-03-06 03:37
I can confirm it's slower. I suspect the BPM differential may be a percentage rather than an absolute number like 20 though.

**Comment by Malethar** [comment] 2016-03-06 03:38
yeah, i just used 20 as a way to compensate for the time being

**Comment by nikita-kiryanov** [comment] 2018-01-13 00:24
I can also report that playback is noticeably slow, and it's like this in all tabs I tried so far. By rough estimation, it's about 25% slower than it should be, and I also noticed that sometimes it suddenly picks up speed, and then slows down again I'm using Windows 10.

**Comment by cameronwhite** [comment] 2020-05-28 00:29
Can you try with the latest release? I suspect #269 might have fixed this.

**Comment by acjay** [comment] 2020-06-09 04:06
I think there are still playback issues with slides, specifically. Things seem fine for bends, but slides cause the tempo to slow down for the duration of the slide. I'm experiencing this on Windows 10.

**Comment by cameronwhite** [comment] 2020-06-09 12:15
Thanks, I think I can reproduce that on OSX. It seems to be more an issue with slides in/out of a note rather than shift/legato slides between notes - does that match what you were seeing?

**Comment by acjay** [comment] 2020-06-09 16:40
I think it's affecting all slides, as far as I can tell

**Comment by cameronwhite** [comment] 2020-06-09 20:49
Yeah, testing on Windows I'm seeing that a bit more, although performance is a bit harder to evaluate on a VM

**Comment by cameronwhite** [comment] 2020-06-09 20:50
Attached is a simple file that I was testing with: 
[slides.zip](https://github.com/powertab/powertabeditor/files/4754790/slides.zip)

**Comment by cameronwhite** [comment] 2020-06-10 02:07
I think this should be fixed with 6604fb5 - I've verified that the wall clock time between notes in that file stays consistently at 500ms (120bpm) now, whereas before it was often drifting up to 540-550ms with some of the slides.

Thanks for all the testing on this!

**Closed by cameronwhite** 2020-06-10 02:07 UTC
Labels: C-midi
