### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by QwertyZW** [powertab/powertabeditor#250] opened 2017-05-31 00:14 UTC
I'm using a build from commit https://github.com/powertab/powertabeditor/commit/23d83fe638ed7201df0e62f49d85bac61cc78e7a
OS: Ubuntu 16.04

Clicking on the green PLAY button summons a vertical red line that goes through the notes but I don't hear anything, not even the metronome. Tried all the playback options available  (Midi Through 14:0, TiMidity 128:0, TiMidity 128:1, TiMidity 128:2, TiMidity 128:3) 

I'm using a youtube video on the side to make sure I actually have sound

All assertions pass
```
khishman@khishman-desktop:~/dev/powertab/build$ ./bin/pte_tests 
===============================================================================
All tests passed (795 assertions in 180 test cases)
```

This is what my console looks like

```
khishman@khishman-desktop:~/dev/powertab/build$ ./bin/powertabeditor 
void DBusMenuExporterPrivate::addAction(QAction*, int): Already tracking action "Remove Note" under id 26
void DBusMenuExporterPrivate::addAction(QAction*, int): Already tracking action "Remove Position" under id 27
Opening file:  "/home/khishman/music/test.pt2"
File loaded in 5 ms
Tab creation started ...
Using 1 worker thread(s)
Score rendered in 22 ms
Rendered  93 items
Tab opened in 29 ms

MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!

QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
```

Here's the pt2 file and several screenshots
[test.pt2.zip](https://github.com/powertab/powertabeditor/files/1039968/test.pt2.zip)

The artificats are the gpu driver's work. Never mind them.
![powertab](https://cloud.githubusercontent.com/assets/8478946/26610187/15c43ae4-4574-11e7-8a2a-d1b48b1c68c7.png)
![powertab2](https://cloud.githubusercontent.com/assets/8478946/26610186/15c12b6a-4574-11e7-9aba-bf82e583c9d9.png)

Cheers mate

**Comment by cameronwhite** [comment] 2017-05-31 01:03
I think when invoking `timidity` on the command line, you can pass it a midi file to play - maybe try that to see if it's something specific to how powertab is sending MIDI events.

**Comment by QwertyZW** [comment] 2017-05-31 02:43
`timidity` from the commandline works

**Comment by QwertyZW** [comment] 2017-06-01 16:48
Messages causing errors:

This message is before midi starts playing (I know from play/stop button and position)
```
[0]:255 '\377'
[1]:81 'Q'
[2]:3 '\003'
[3]:7 '\a'
[4]:161 '\241'
[5]:32 ' '
```

This message appears 3 times after playing stops.
```
[0]:255 '\377'
[1]:47 '/'
[2]:0 '\000'
```
```
[0]:255 '\377'
[1]:47 '/'
[2]:0 '\000'
```
```
[0]:255 '\377'
[1]:47 '/'
[2]:0 '\000'
```

**Comment by embatbr** [comment] 2017-11-26 02:29
Same problem here. My console:

```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock

MidiOutJack::initialize: JACK server not running?


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!


MidiOutAlsa::sendMessage: event parsing error!```

**Comment by cameronwhite** [comment] 2020-06-10 02:28
I tried in an Ubuntu 20.04 VM and got it working by installing `timidity-daemon` and running `sudo service timidity restart` to kick things off. Alternatively, running `timidity -iA` manually  works too.
Are you able to get it working with either of those approaches?

I think the `event parsing error` is from the "track end" meta message, which should be fixed but I think is harmless.

**Comment by luzpaz** [comment] 2023-12-15 10:00
Is this issue still relevant ?

**Closed** 2023-12-15 18:56 UTC
Labels: bug, C-midi, help wanted

**Comment by Vitalii-Kh95** [comment] 2024-12-21 19:34
Having same problem
/usr/local/bin/powertabeditor
Finding translations for locale QLocale(English, Latin, United States) with UI languages QList("en-US", "en-Latn-US", "en")
  - Checking "/home/vitalii/.local/share/powertab/powertabeditor/translations"
  - Checking "/usr/share/plasma/powertab/powertabeditor/translations"
  - Checking "/home/vitalii/.local/share/flatpak/exports/share/powertab/powertabeditor/translations"
  - Checking "/var/lib/flatpak/exports/share/powertab/powertabeditor/translations"
  - Checking "/usr/local/share/powertab/powertabeditor/translations"
  - Checking "/usr/share/powertab/powertabeditor/translations"
  - Checking "/var/lib/snapd/desktop/powertab/powertabeditor/translations"
  - Checking "/usr/local/bin/data/translations"
  - Checking "/usr/share/qt6/translations"
Loaded Qt base translations from "/usr/share/qt6/translations/qtbase_en.qm"

MidiOutJack::initialize: JACK server not running?

**Comment by cameronwhite** [comment] 2024-12-21 23:35
Do you have timidity or some other MIDI sequencer (either for JACK or ALSA) set up?

**Comment by Vitalii-Kh95** [comment] 2024-12-22 13:13
> Do you have timidity or some other MIDI sequencer (either for JACK or ALSA) set up?

Executing command: timidity <filename> plays it, If that's the questions.

**Comment by cameronwhite** [comment] 2024-12-22 21:57
> > Do you have timidity or some other MIDI sequencer (either for JACK or ALSA) set up?
> 
> Executing command: `timidity <filename> `plays it, If that's the question.

OK thanks - are there any MIDI ports available if you open the preferences dialog? I think timidity needs to be running as a daemon if that's the midi sequencer you're using

**Comment by Vitalii-Kh95** [comment] 2024-12-23 10:09
> OK thanks - are there any MIDI ports available if you open the preferences dialog? I think timidity needs to be running as a daemon if that's the midi sequencer you're using
There's something in preferences, I am not sure what it is though. I attached screenshot of the window.
It should be the problem since command `systemctl status timidity`
Gives this:
`Active: active (exited) since Mon 2024-12-23 14:54:59 +05; 8min ago`
And as far as I understand it should be  active (running). Right?
I am not an experienced linux user and I don't understand what to do next. There's no doc page on timidity.
![Screenshot_20241223_104412](https://github.com/user-attachments/assets/ad9548b0-ed26-4906-928c-f2aea72239e6)

**Comment by cameronwhite** [comment] 2024-12-23 17:58
Yeah, I think I'd expect the status to say `running` so you could try restarting it?
In the preferences dialog, if it's working correctly there should be more options in the `MIDI Output Device` menu which let you choose a MIDI port from timidity

**Comment by Vitalii-Kh95** [comment] 2024-12-24 06:28
> Yeah, I think I'd expect the status to say `running` so you could try restarting it? In the preferences dialog, if it's working correctly there should be more options in the `MIDI Output Device` menu which let you choose a MIDI port from timidity

Apparently I have some problems with timidity. I couldn't set it up,, the program crashes when I try to follow configuration recommendations from internet. Is there an alternative to using timidity?

**Comment by cameronwhite** [comment] 2024-12-24 17:36
I've mainly used timidity, but any ALSA software synthesizer should work so something like FluidSynth is an option too

**Comment by psyomn** [comment] 2024-12-25 05:26
Hello:

Not sure if you're able to, but could you try this out?

Open a terminal and enter the following:

        timidity -iA -Os

If timidity can run properly, you should see something like this:

        ***@***.*** ~]$ timidity -iA -Os
        Requested buffer size 32768, fragment size 8192
        ALSA pcm 'default' set buffer size 32768, period size 8192 bytes
        TiMidity starting in ALSA server mode
        Opening sequencer port: 128:0 128:1 128:2 128:3

Now, leave that terminal open, and try setting a timidity port in the
settings menu on powertab editor, and then press play.

I think the only other thing that might be missing could be default
soundfonts; though if you're able to play midis on the command line you
should probably be good on that front.

**Comment by Vitalii-Kh95** [comment] 2025-01-24 12:07
> Open a terminal and enter the following: timidity -iA -Os

timidity -iA -Os
Segmentation fault (core dumped)

Sorry for late reply—I missed notification. Also, It felt like too many problems for me to deal with for a musical app.

With these flags, TiMidity throws an error. Could it be caused by another dependency? I’ve tried various installation methods, including using Flatpak and building from source manually. This might suggest some insufficiency in the setup instructions.

**Comment by psyomn** [comment] 2025-01-29 05:29
Hello:

That is pretty odd.  I've personally never witnessed timidity crash like
that.

On Fri, Jan 24, 2025 at 04:07:57AM GMT, Vitaliy wrote:
> With these flags, TiMidity throws an error. Could it be caused by
> another dependency? I’ve tried various installation methods, including
> using Flatpak and building from source manually. This might suggest
> some insufficiency in the setup instructions.

My gut feeling here is there is some misconfiguration somewhere
happening, and said configuration is making timidity crash (like reading
a bad file/format).  For completeness sake, what does this command give
you if you run it?

        $ timidity --version
        TiMidity++ version 2.15.0

This is what my configuration looks like:

        $ cat /etc/timidity/timidity.cfg
        # details on this file and other examples see here:
        # http://www.onicos.com/staff/iz/timidity/dist/cfg/sndfont.cfg
        # http://www.onicos.com/staff/iz/timidity/dist/cfg/
        #----------------------------------------------------------------
        # SoundFont extension configuration
        #
        # soundfont <filename> [order={0|1}] [remove]
        #    <filename> is the path of SoundFont file.
        #    order: 0(preload) or 1(load after GUS).
        #    remove: disable specified soundfont.
        #
        # font exclude <tonebank> [<preset> [<keynote>]]
        # font order {0|1} <tonebank> [<preset> [<keynote>]]
        #    <tonebank>: 0-127
        #
        # font exclude 128 [<drumset> [<key>]]
        # font order {0|1} 128 [<drumset> [<key>]]
        #----------------------------------------------------------------

        # change the next line to point to a soundfont you have
        # soundfonts can be found e.g. here: http://www.hammersound.net/
        # soundfont /usr/share/soundfonts/DX7Piano.SF2

        # you can do manipulations of the soundfont you load like this:
        # e.g. removing drumset 99
        # font exclude 128 99

        # load drum samples after GUS patches
        # font order 1 128
        soundfont /usr/share/soundfonts/FluidR3_GM.sf2

        $ ls /usr/share/soundfonts/
        FluidR3_GM.sf2  FluidR3_GS.sf2

And just to be sure:

        $ file /usr/share/soundfonts/*
        /usr/share/soundfonts/FluidR3_GM.sf2: RIFF (little-endian) data, SoundFont/Bank
        /usr/share/soundfonts/FluidR3_GS.sf2: RIFF (little-endian) data, SoundFont/Bank

Try out the above commands and see if you're getting similar output to
mine.  Your /etc/ timidity file path may vary.

I don't know how much time/effort you want to spend on this, but if you
have gdb (you can install it from a package manager if not), could you
run the following command?  (It's cool if this is too much work).

        $ gdb --args timidity -iA -Os

Once timidity crashes, you should be in the gdb instance, and you should
be able to invoke `bt' like this (the backtrace is an example):

        (gdb) bt
        #0  __GI___clock_nanosleep ***@***.***=0, ***@***.***=0, ***@***.***=0x7ffc92bb8d00, ***@***.***=0x0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:71
        #1  0x00007bd6d84a9827 in __GI___nanosleep ***@***.***=0x7ffc92bb8d00, ***@***.***=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:25
        #2  0x00007bd6d84d4f9a in usleep (useconds=<optimized out>) at ../sysdeps/posix/usleep.c:31
        #3  0x00006374c4dd31a5 in b () at sample.c:16
        #4  0x00006374c4dd3242 in main () at sample.c:35

That might give some hints as to why timidity is crashing... though I
suspect it might be more work than it is worth to figure out.

Take care!
