### ISSUE TITLE
The system plays Voice #2 notes before they are supposed to be played.  

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#426] opened 2023-01-01 19:38 UTC
**Description**
A description of what the bug is.

**To Reproduce**
Steps to reproduce the issue.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
If applicable, include your operating system (e.g. Windows 10) and which version of Power Tab Editor (e.g. Alpha 12) you are using

**Comment by cameronwhite** [comment] 2023-01-01 20:20
This sounds like a duplicate of #422, which still requires an example file to reproduce the issue

**Closed by cameronwhite** 2023-01-01 20:20 UTC
Labels: bug
