### ISSUE TITLE
The notes on the staff of Voice 1 are down, not up in my piece.

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#429] opened 2023-01-03 00:56 UTC
When I publish tablatures, I've had complaints from people that the staff notes are pointing in the wrong direction and I now realize that it's true.  Why did this happen?  Can it be fixed in a piece?

**To Reproduce**
Steps to reproduce the issue.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
If applicable, include your operating system (e.g. Windows 10) and which version of Power Tab Editor (e.g. Alpha 12) you are using

**Comment by cameronwhite** [comment] 2023-01-03 03:27
I think this is a bug - sounds like a duplicate of #62

**Closed by cameronwhite** 2023-01-03 03:27 UTC
Labels: bug
