### ISSUE TITLE
Has widescreen support been added yet?

### ISSUE THREAD

**Issue by Bamboozaler** [powertab/powertabeditor#316] opened 2020-12-02 23:34 UTC
I have a 32:9 monitor and would love to see the music extended wide and horizontal rather than having to always scroll vertically. I know guitar pro can do this but I much prefer power tab 2.0. Are there any plans to add this feature? I couldn't find anything in the settings.

**Comment by cameronwhite** [comment] 2020-12-03 22:58
Not yet, I think this would be a duplicate of #50 
This probably would require showing multiple systems side-by-side and perhaps configuring the system width

**Closed by cameronwhite** 2020-12-03 22:58 UTC
