### ISSUE TITLE
Error initializing MIDI output device

### ISSUE THREAD

**Issue by francheton** [powertab/powertabeditor#246] opened 2017-05-13 04:02 UTC
Hello,

I just upgraded my PowerTabEditor from 1.7.0 to 2.0.0 alpha 10 under windows 10.

When I load all the .ptb files I previously build with the older version, I obtain this message : 

"error initializing MIDI output device"

=> Who can help me ?

Best regards.

**Comment by DontBelieveMe** [comment] 2017-05-14 11:32
Can you link/attach an example of a ptb file that causes the crash?

**Comment by alfredowl** [comment] 2019-11-19 16:17
I am experiencing the same problem.  when I got to set the midi output device /File/Preferences/Midi there are no items in the drop down for 'Midi Output Device'.  Any help would be much appreciated.

thanks,

**Comment by joeSeggiola** [comment] 2020-05-30 15:31
Hi @alfredowl , have you fixed somehow? I have the exact same issue, I tried installing a MIDI mapper and a MIDI synth, but nothing changed...

**Comment by joeSeggiola** [comment] 2020-05-30 15:53
Ok, looks like there's something wrong in beta 11. I uninstalled and re-installed beta 10, now it plays! In File > Preferences > Midi Output Device I can see a device, where in bete 11 there was nothing.

**Comment by cameronwhite** [comment] 2020-05-30 16:04
Interesting, I'll see if I can reproduce the same in my windows VM. I think the main thing that would have changed in alpha 11 was upgrading to a newer version of the RtMidi library

**Comment by joeSeggiola** [comment] 2020-05-30 16:12
@cameronwhite Also, beta 10 plays fine, but can't open my old PTB files (PowerTab 1.7), I can send you privately an example via email if you like. The same file opens fine with beta 11, so I tried to save a PT2 from there and open it in beta 10, but it fails (but I guess it's normal since it's an older version of the saved file...?).

**Comment by cameronwhite** [comment] 2020-05-30 16:20
Yeah, I think the file format version number was bumped in alpha 11 due to adding left hand fingerings. I wasn't aware of any issues that were fixed with opening old ptb files, though, so I'd be interested to see a file that had an issue

**Comment by joeSeggiola** [comment] 2020-05-30 16:27
@cameronwhite Ok, I'm sending it to you now, to the email I see on your GitHub profile.

> I think the file format version number was bumped in alpha 11

Yes, I saw that `"version": 4`, I tried to manually change to `"version": 3` (a man can hope!) but it didn't work... :smile:

**Comment by cameronwhite** [comment] 2020-05-30 17:09
Thanks, got the email!

**Comment by acjay** [comment] 2020-05-31 05:46
Same problem with Alpha 11 on Windows 10. I uninstalled and installed Alpha 10 and playback works fine.

**Comment by cameronwhite** [comment] 2020-05-31 23:15
I can repro on my VM and am looking into it

@joeSeggiola - Based on the file you sent, I think the issue opening that file in alpha 10 is the non-ASCII characters in the file name, which #244 fixed

**Comment by cameronwhite** [comment] 2020-06-01 00:35
Ah, I think the issue is that the vcpkg build of RtMidi isn't configured correctly - https://github.com/microsoft/vcpkg/issues/6993

**Comment by cameronwhite** [comment] 2020-06-02 01:03
OK, the midi issues on Windows should be fixed now!
I've updated the alpha 11 release with a new Windows build that incorporates those changes.

**Closed by cameronwhite** 2020-06-02 01:03 UTC
Labels: C-midi, E-help-wanted
