### ISSUE TITLE
I just created a new file with tempo at 120 but it plays back at only about 40, another bug

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#415] opened 2022-12-03 20:14 UTC
**Description**
A description of what the bug is.

**To Reproduce**
Steps to reproduce the issue.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
If applicable, include your operating system (e.g. Windows 10) and which version of Power Tab Editor (e.g. Alpha 12) you are using

**Comment by cameronwhite** [comment] 2022-12-06 02:50
Could you attach a file that demonstrates this issue? I could not reproduce this by creating a new file with the default tempo of 120

**Comment by cameronwhite** [comment] 2023-07-16 02:33
Closing as this could not be reproduced

**Closed by cameronwhite** 2023-07-16 02:33 UTC
Labels: bug, info needed
