### ISSUE TITLE
Pitch shifted unexpectly when start to play from the middle of the score

### ISSUE THREAD

**Issue by NalihznehC** [powertab/powertabeditor#395] opened 2022-09-29 07:13 UTC
**Description**
I added many slides inside my tab, maybe those slides went wrong while start playing from the midst of tab.

**To Reproduce**
[花降らしMidiExp202209290002.zip](https://github.com/powertab/powertabeditor/files/9671925/MidiExp202209290002.zip)
![image](https://user-images.githubusercontent.com/39670573/192963252-014bb966-3036-4494-9902-1d332eaafa7e.png)
Open the .pt2 file and navigate to the 18th bar and press spacebar to play, the violin (vocal) will be out of tune (sometimes lead guitar will also be weirdly shifted)

**Additional Info**
I cannot find its bug pattern as listening to the bug is a torture to my ears. The report also looks less elegant, sorry for that.
[花降らし(Part1).zip](https://github.com/powertab/powertabeditor/files/9671941/Part1.zip)
This is what it should sound like (exported perfectly and buglessly from Power Tab Editor (alpha18-51-gf11404c3)).

**Version**
Windows 10 21H2
Power Tab Editor 2.0 Beta (v2.0.0-alpha18-51-gf11404c3)

**Comment by NalihznehC** [comment] 2022-09-29 07:18
https://user-images.githubusercontent.com/39670573/192965471-303bd617-0c2a-4e34-bf2f-d3ed72e43562.mp4

Here is the torture.

**Comment by wwhhff** [comment] 2022-09-29 21:51
I encountered the same issue which @NalihznehC has mentioned. The note sounds randomly out of tune when starting the playback in the middle of a song.

**Comment by cameronwhite** [comment] 2022-09-30 02:38
I haven't been able to reproduce this yet (on macOS), but thank you for all the details! It does sound like an issue with the midi pitch wheel not being reset, or something similar

**Comment by BigHonkinDaddy** [comment] 2022-10-13 13:04
Yes, this is definitely an issue that I've seen often.  Its not random.  if you start the midi player AFTER a slide, the pitch will be offset by the same amount as the prior slide... if the slide was up 4 half steps, the pitch of the notes (if you start the midi player after that slide) will be sharp by 4 half steps.  I will attach a short sample powertab score as an example that might help reproduce the issue.
[Bug Example - Slide.zip](https://github.com/powertab/powertabeditor/files/9776894/Bug.Example.-.Slide.zip)

**Comment by cameronwhite** [comment] 2022-10-14 01:57
Thanks for the file - I still couldn't reproduce it on macOS, but I do get the issue on Windows so I'll look into it further there

**Comment by cameronwhite** [comment] 2022-10-16 17:53
I think I've got a fix for this, but more testing would be appreciated! The latest build can be downloaded from https://github.com/powertab/powertabeditor/actions/runs/3260359815 once it's finished building

**Closed** 2022-10-16 17:53 UTC
Labels: bug, C-midi

**Comment by BigHonkinDaddy** [comment] 2022-10-17 12:33
Your fix seems to be working.  I tried it out on several of my tabs and its working great.  Windows 10 x64.
