### ISSUE TITLE
Copy/Paste bar lines

### ISSUE THREAD

**Issue by BigHonkinDaddy** [powertab/powertabeditor#336] opened 2021-09-02 16:21 UTC
**Description**
When copying notes from one system and pasting to another, would be very helpful to include the barlines with the notes.  I assume the current behavior to omit the barlines when copying/pasting notes is a "feature" and not a "bug" so making this an "enhancement" issue.

**Comment by cameronwhite** [comment] 2021-09-09 02:04
This is a duplicate of #208

**Closed by cameronwhite** 2021-09-09 02:04 UTC
Labels: enhancement
