### ISSUE TITLE
Crash on Playback (Windows)

### ISSUE THREAD

**Issue by ccnicholls** [powertab/powertabeditor#179] opened 2015-05-29 18:13 UTC
Windows 7 SP1 
Running Alpha 7

Imported legacy pt file
Saved as new pt2 file
Hit play button

Crash.  Here's the Event Log entry

Log Name:      Application
Source:        Application Error
Date:          5/29/2015 10:31:48 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      XXXXXXX
Description:
Faulting application name: powertabeditor.exe, version: 2.0.0.0, time stamp: 0x553c6a11
Faulting module name: powertabeditor.exe, version: 2.0.0.0, time stamp: 0x553c6a11
Exception code: 0xc0000005
Fault offset: 0x000000000008a956
Faulting process id: 0x117c
Faulting application start time: 0x01d09a350afe4731
Faulting application path: C:\Program Files\Power Tab\Power Tab Editor\powertabeditor.exe
Faulting module path: C:\Program Files\Power Tab\Power Tab Editor\powertabeditor.exe
Report Id: 94ded4ee-0628-11e5-9983-5cc5d49979b4
Event Xml:

`<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-05-29T17:31:48.000000000Z" />
    <EventRecordID>4768</EventRecordID>
    <Channel>Application</Channel>
    <Computer>XXXXXXX</Computer>
    <Security />
  </System>
  <EventData>
    <Data>powertabeditor.exe</Data>
    <Data>2.0.0.0</Data>
    <Data>553c6a11</Data>
    <Data>powertabeditor.exe</Data>
    <Data>2.0.0.0</Data>
    <Data>553c6a11</Data>
    <Data>c0000005</Data>
    <Data>000000000008a956</Data>
    <Data>117c</Data>
    <Data>01d09a350afe4731</Data>
    <Data>C:\Program Files\Power Tab\Power Tab Editor\powertabeditor.exe</Data>
    <Data>C:\Program Files\Power Tab\Power Tab Editor\powertabeditor.exe</Data>
    <Data>94ded4ee-0628-11e5-9983-5cc5d49979b4</Data>
  </EventData>
</Event>`

**Comment by cameronwhite** [comment] 2015-05-30 04:10
Would you be able to provide the file that caused the crash? The event log information isn't too helpful for determining where exactly the problem is

**Comment by ccnicholls** [comment] 2015-05-30 04:41
Go to tablibrary.com. search for heaven and hell by Black Sabbath. Download top listed powertab file.

**Comment by cameronwhite** [comment] 2015-05-30 04:50
OK, thanks - I can reproduce the crash.

**Comment by cameronwhite** [comment] 2015-05-30 17:33
It looks like this was already fixed by https://github.com/powertab/powertabeditor/commit/3ce788f3, so it'll be fixed in the next alpha release

**Closed by cameronwhite** 2015-05-30 17:33 UTC
Labels: C-crash, C-midi, T-bug
